site_name: Terraform GKE Private Deployment
site_description: Documentation for Terraform-based private GKE cluster deployment
site_author: DevOps Team
site_url: http://localhost:8000

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - Implementation Plan: implementation-plan.md
  - Architecture: architecture.md
  - Modules:
      - GKE Module: modules/gke.md
      - Helm App Module: modules/helm-app.md
  - Examples:
      - Development Environment: examples/dev.md
  - Deployment Guide: deployment-guide.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/badara10/terraform-gke-private-deployment

plugins:
  - search
  - minify:
      minify_html: true